.backend-docker-build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  tags:
    - roboticon-live
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/backend --dockerfile $CI_PROJECT_DIR/backend/$DOCKERFILE --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG

backend-docker-build-application:
  extends: .backend-docker-build
  variables: 
    DOCKERFILE: "Dockerfile-app"
    IMAGE_NAME: "application"
    GIT_SUBMODULE_STRATEGY: recursive

backend-docker-build-migrations:
  extends: .backend-docker-build
  variables: 
    DOCKERFILE: "Dockerfile-migrations"
    IMAGE_NAME: "migrations"
