.backend-docker-build:
  image: docker:latest
  stage: build
  image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    tags:
        - roboticon-live
        - docker
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context $CI_PROJECT_DIR/backend --dockerfile $CI_PROJECT_DIR/backend/$IMAGE_NAME --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG

backend-docker-build-application:
  extends: .backend-docker-build
  variables: 
    DOCKERFILE: "Dockerfile-app"
    IMAGE_NAME: "application"

backend-docker-build-migrations:
  extends: .backend-docker-build
  variables: 
    DOCKERFILE: "Dockerfile-migrations"
    IMAGE_NAME: "migrations"
